<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ModularMonolithTemplate.Billing.Presentation</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="MediatR" Version="13.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../ModularMonolithTemplate.Billing.Infrastructure/ModularMonolithTemplate.Billing.Infrastructure.csproj" />
    </ItemGroup>

</Project>
