<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Billing\Application\" />
      <Folder Include="Billing\Contracts\" />
      <Folder Include="Billing\Domain\" />
      <Folder Include="Billing\Infra\" />
      <Folder Include="Billing\Presentation\" />
      <Folder Include="Catalog\Domain\" />
      <Folder Include="Catalog\Infra\" />
      <Folder Include="Catalog\Presentation\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Tests\Class1.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Tests\Class1.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Presentation\Controllers\CatalogController.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Presentation\Controllers\CatalogController.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Presentation\Controllers\CatalogReadController.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Presentation\Controllers\CatalogReadController.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Contracts\Class1.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Contracts\Class1.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Domain\Projections\CatalogInvoice.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Domain\Projections\CatalogInvoice.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Infrastructure\Persistence\CatalogReadDbContext.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Infrastructure\Persistence\CatalogReadDbContext.cs</Link>
      </Compile>
      <Compile Update="Catalog\ModularMonolithTemplate.Catalog.Infrastructure\Persistence\CatalogWriteDbContext.cs">
        <Link>Catalog\ModularMonolithTemplate.Billing.Infrastructure\Persistence\CatalogWriteDbContext.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="Catalog\ModularMonolithTemplate.Catalog.Tests\Integration\.gitkeep">
        <Link>Catalog\ModularMonolithTemplate.Billing.Tests\Integration\.gitkeep</Link>
      </None>
      <None Update="Catalog\ModularMonolithTemplate.Catalog.Tests\Unit\.gitkeep">
        <Link>Catalog\ModularMonolithTemplate.Billing.Tests\Unit\.gitkeep</Link>
      </None>
    </ItemGroup>

</Project>
