<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Billing\Contracts\" />
      <Folder Include="Catalog\Contracts\" />
      <Folder Include="Catalog\Infra\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

</Project>
